trigger:
- main

pool:
  name: Default

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: NuGetAuthenticate@1

- script: dotnet restore StringExtensionsLib/StringExtensionsLib/StringExtensionsLib.csproj
  displayName: Restore

- script: dotnet build StringExtensionsLib/StringExtensionsLib/StringExtensionsLib.csproj --configuration Release
  displayName: Build

- script: dotnet pack StringExtensionsLib/StringExtensionsLib/StringExtensionsLib.csproj --configuration Release -o $(Build.ArtifactStagingDirectory)
  displayName: Pack

- script: |
    dotnet nuget push "$(Build.ArtifactStagingDirectory)/*.nupkg" \
    --source "https://pkgs.dev.azure.com/vvora1/Lab4/_packaging/lab4-feed/nuget/v3/index.json" \
    --api-key AzureDevOps
  displayName: Push Package
